# Generated by Django 2.2.4 on 2019-10-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
