# Generated by Django 2.2.4 on 2019-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191029_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentannotation',
            options={'ordering': ['global_start_offset', 'id']},
        ),
        migrations.AlterModelOptions(
            name='contentnode',
            options={'ordering': ['ordinals']},
        ),
        migrations.AlterField(
            model_name='contentannotation',
            name='kind',
            field=models.CharField(choices=[('replace', 'replace'), ('highlight', 'highlight'), ('elide', 'elide'), ('note', 'note'), ('link', 'link')], max_length=255),
        ),
    ]
