# Generated by Django 2.2.4 on 2019-11-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191118_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentannotation',
            name='end_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentannotation',
            name='start_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentannotation',
            name='start_paragraph',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
