# Generated by Django 2.2.8 on 2019-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191205_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_login_at',
            field=models.DateTimeField(blank=True, help_text='Time of most recent password login', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_login_ip',
            field=models.CharField(blank=True, help_text='IP of most recent password login', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, help_text='Time of previous password login', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(blank=True, help_text='IP of previous password login', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_request_at',
            field=models.DateTimeField(blank=True, help_text='Time of last request from user (to nearest 10 minutes)', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Number of explicit password logins by user'),
        ),
    ]
