# Generated by Django 2.2.9 on 2019-12-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191211_1600'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='ArInternalMetadata',
        ),
        migrations.DeleteModel(
            name='Collage',
        ),
        migrations.DeleteModel(
            name='DelayedJob',
        ),
        migrations.DeleteModel(
            name='FrozenItem',
        ),
        migrations.DeleteModel(
            name='Metadata',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='PermissionAssignment',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='PlaylistItem',
        ),
        migrations.DeleteModel(
            name='PlaylistsUserCollection',
        ),
        migrations.DeleteModel(
            name='SchemaMigration',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tagging',
        ),
        migrations.RemoveField(
            model_name='unpublishedrevision',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='unpublishedrevision',
            name='casebook',
        ),
        migrations.RemoveField(
            model_name='unpublishedrevision',
            name='node',
        ),
        migrations.RemoveField(
            model_name='unpublishedrevision',
            name='node_parent',
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
        migrations.DeleteModel(
            name='UserCollectionsUser',
        ),
        migrations.DeleteModel(
            name='UnpublishedRevision',
        ),
    ]
