# Generated by Django 2.2.9 on 2019-12-19 16:21
from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.utils.crypto import get_random_string

from ..hashers import PBKDF2WrappedRailsPasswordHasher


def forwards_func(apps, schema_editor):
    """
        Password migration via https://docs.djangoproject.com/en/2.2/topics/auth/passwords/#password-upgrading-without-requiring-a-login
    """
    User = apps.get_model('main', 'User')
    hasher = PBKDF2WrappedRailsPasswordHasher()
    for user in User.objects.all():
        if user.crypted_password:
            user.password = hasher.encode_rails_hash(user.crypted_password, user.password_salt)
        else:
            user.password = make_password(get_random_string(20))
        user.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_user_password'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
