# Generated by Django 2.2.9 on 2019-12-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191219_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default',
            name='created_via_import',
        ),
    ]
