# Generated by Django 2.2.9 on 2019-12-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191219_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='crypted_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_salt',
        ),
    ]
