# Generated by Django 2.2.9 on 2019-12-19 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191219_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentcollaborator',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('editor', 'editor')], max_length=255),
        ),
        migrations.AlterField(
            model_name='contentcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
