# Generated by Django 2.2.9 on 2019-12-19 18:23

from django.db import migrations

def delete_unused_links(apps, schema_editor):
    Default = apps.get_model('main', 'Default')
    Resource = apps.get_model('main', 'Resource')
    Default.objects.exclude(id__in=Resource.objects.filter(resource_type='Default').values('resource_id')).delete()

def delete_unused_textblocks(apps, schema_editor):
    TextBlock = apps.get_model('main', 'TextBlock')
    Resource = apps.get_model('main', 'Resource')
    TextBlock.objects.exclude(id__in=Resource.objects.filter(resource_type='TextBlock').values('resource_id')).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191219_1811'),
    ]

    operations = [
        migrations.RunPython(delete_unused_links),
        migrations.RunPython(delete_unused_textblocks),
    ]
