# Generated by Django 2.2.9 on 2019-12-19 19:40

from django.db import migrations

def delete_legacy_roles(apps, schema_editor):
    """
        There are only two meaningful roles, presently: superadmin and case_admin.
        The other ~154 in the table are 'rep'(1) and 'asker' for 153 different questions.
    """
    Role = apps.get_model('main', 'Role')
    Role.objects.exclude(name__in=['superadmin', 'case_admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20191219_1823'),
    ]

    operations = [
        migrations.RunPython(delete_legacy_roles),
    ]
