# Generated by Django 2.2.9 on 2019-12-19 20:09

from django.db import migrations


def title_to_attribution(apps, schema_editor):
    User = apps.get_model('main', 'User')
    title_no_attribution = User.objects.filter(attribution='').exclude(title='').exclude(title__isnull=True)
    for user in title_no_attribution:
        user.attribution = user.title
        user.save()


def still_no_attribution(apps, schema_editor):
    User = apps.get_model('main', 'User')
    still_no_attribution = User.objects.filter(attribution='')
    still_no_attribution.update(attribution='Anonymous')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191219_2002'),
    ]

    operations = [
        migrations.RunPython(title_to_attribution),
        migrations.RunPython(still_no_attribution),
    ]
