source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 1.2'

# Note: 3.2.1. has a bug that causes chain of UPDATE/DELETEs on annotations tagged when required tag removed
gem 'acts-as-taggable-on', '~> 3.1.1'  

gem 'authlogic'
gem 'ancestry'
gem 'progress_bar'
gem 'sunspot_rails'
gem 'dropbox-sdk'
gem 'will_paginate'
gem 'RedCloth'
gem 'formtastic', '~> 2.3.0.rc2'
gem 'nokogiri', '~> 1.6'
gem 'actionpack-page_caching'
gem 'exception_notification'
gem 'rails-observers'
gem 'fastercsv'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'daemons', '1.0.10'
gem 'rails_admin'
gem 'cancan'
gem 'kaminari'
gem 'recaptcha'
gem 'paperclip'
gem 'ckeditor'
gem 'warden'
gem 'bcrypt'
gem 'scrypt'
gem 'rails_admin_import', '0.1.9'
gem 'loofah-activerecord', '~> 1.2'

group :development do
  gem 'sunspot_solr'
  gem 'quiet_assets'
  gem 'rspec-rails'
end
