# Generated by Django 2.2.16 on 2020-10-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0072_auto_20201015_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='jurisdiction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='jurisdiction_slug',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='jurisdiction_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='jurisdiction_slug',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
