# Generated by Django 2.2.16 on 2020-10-21 14:44

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201021_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocumentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_class', models.CharField(blank=True, max_length=100, null=True)),
                ('citations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), size=None)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('source_ref', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=5242880)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete='DO_NOTHING', related_name='documents', to='main.LegalDocumentSource')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLegalDocument',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_class', models.CharField(blank=True, max_length=100, null=True)),
                ('citations', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500, null=True), size=None)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('source_ref', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=5242880)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.LegalDocumentSource')),
            ],
            options={
                'verbose_name': 'historical legal document',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='USCodeIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('gpo_id', models.CharField(max_length=255)),
                ('citation', models.CharField(max_length=255)),
                ('lii_url', models.URLField(null=True)),
                ('gpo_url', models.URLField(null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('search_field', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('document', django.contrib.postgres.search.SearchVectorField()),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'internal_search_view',
                'managed': False,
            },
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=django.contrib.postgres.indexes.GinIndex(fields=['citations'], name='main_legald_citatio_34c035_gin'),
        ),
    ]
