# Generated by Django 2.2.19 on 2021-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alternate_legal_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legaldocumentsource',
            name='enabled',
        ),
        migrations.AddField(
            model_name='legaldocumentsource',
            name='priority',
            field=models.IntegerField(null=True),
        ),
    ]
