# Generated by Django 2.2.20 on 2021-04-16 00:42

from django.db import migrations, models

def check_repealed(apps, schema_editor):
    USCodeIndex = apps.get_model('main', 'USCodeIndex')
    for ind in USCodeIndex.objects.all():
        ind.repealed = ind.title.startswith("Repealed")
        ind.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210414_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='uscodeindex',
            name='repealed',
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(check_repealed)
    ]
