# Generated by Django 2.2.4 on 2019-12-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191122_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='attribution',
            field=models.CharField(default='Anonymous', max_length=255, verbose_name='Display name'),
        ),
    ]
