# Generated by Django 2.2.21 on 2021-05-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_savedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedimage',
            name='alt_text',
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
