# Generated by Django 2.2.9 on 2019-12-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191211_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='UNSET', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
