# Generated by Django 2.2.21 on 2021-05-12 02:17

from django.db import migrations, models
import main.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210511_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedimage',
            name='file_name',
        ),
        migrations.AddField(
            model_name='savedimage',
            name='image',
            field=models.FileField(default=None, storage=main.storages.S3Storage(access_key='accesskey', bucket_name='h2o.images', endpoint_url='http://minio:9000', secret_key='secretkey'), upload_to=''),
            preserve_default=False,
        ),
    ]
