# Generated by Django 2.2.21 on 2021-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210512_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedimage',
            name='external_id',
            field=models.UUIDField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='savedimage',
            index=models.Index(fields=['external_id'], name='main_savedi_externa_97e5f9_idx'),
        ),
    ]
