# Generated by Django 2.2.24 on 2021-09-14 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210805_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentannotation',
            name='kind',
            field=models.CharField(choices=[('replace', 'replace'), ('highlight', 'highlight'), ('elide', 'elide'), ('note', 'note'), ('link', 'link'), ('correction', 'correction')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcontentannotation',
            name='kind',
            field=models.CharField(choices=[('replace', 'replace'), ('highlight', 'highlight'), ('elide', 'elide'), ('note', 'note'), ('link', 'link'), ('correction', 'correction')], max_length=255),
        ),
        migrations.CreateModel(
            name='CasebookEditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('change', models.CharField(choices=[('Removed', 'REMOVED'), ('Added', 'ADDED'), ('Edited', 'EDITED'), ('Annotated', 'ANNOTATED'), ('First', 'ORIGINAL_PUBLISH')], max_length=10)),
                ('casebook', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='edit_log', to='main.Casebook')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_log', to='main.ContentNode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
