# Generated by Django 2.2.24 on 2021-10-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_casebookfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebook',
            name='export_fails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalcasebook',
            name='export_fails',
            field=models.IntegerField(default=0),
        ),
    ]
