# Generated by Django 2.2.24 on 2021-10-14 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211007_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.DeleteModel(
            name='HistoricalCase',
        ),
    ]
