# Generated by Django 2.2.24 on 2021-10-25 21:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20211014_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='display_ordinals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='does_display_ordinals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcontentnode',
            name='display_ordinals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='historicalcontentnode',
            name='does_display_ordinals',
            field=models.BooleanField(default=True),
        ),
    ]
