# Generated by Django 2.2.24 on 2021-11-30 19:58

from django.db import migrations
from django.db.models import F


def populate_display_ordinals(apps, schema_editor):
    ContentNode = apps.get_model('main', 'ContentNode')
    if not ContentNode.objects.exclude(display_ordinals=[]).exists():
        ContentNode.objects.all().update(display_ordinals=F('ordinals'))


def unset_display_ordinals(apps, schema_editor):
    ContentNode = apps.get_model('main', 'ContentNode')
    ContentNode.objects.all().update(display_ordinals=[])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20211025_2147'),
    ]

    operations = [
        migrations.RunPython(populate_display_ordinals, unset_display_ordinals),
    ]
