# Generated by Django 2.2.24 on 2021-11-30 22:36

from django.contrib.postgres.fields import JSONField
from django.db import migrations
from django.db.models import F, Func, Value
from django.utils import timezone

from main.models import CAP

def add_footnote_metadata(apps, schema_editor):
    LegalDocument = apps.get_model('main', 'LegalDocument')
    for i, regex in enumerate(CAP.details['footnote_regexes']):
        rows = LegalDocument.objects.filter(content__regex=regex).update(metadata=Func(
            F("metadata"),
            Value(["html_info"]),
            Value({'footnotes': {'style': 'cap', 'regex': regex, 'last_checked_timestamp': timezone.now().timestamp()}}, JSONField()),
            function="jsonb_set",
        ))
        print(f'\n({i}) Updated {rows} records.')


def drop_footnote_metadata(apps, schema_editor):
    LegalDocument = apps.get_model('main', 'LegalDocument')
    for doc in LegalDocument.objects.all():
        doc.metadata.pop('html_info', None)
        doc.save(update_fields=['metadata'])



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211130_2114'),
    ]

    operations = [
        migrations.RunPython(add_footnote_metadata, drop_footnote_metadata),
    ]



