# Generated by Django 2.2.26 on 2022-01-10 20:23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20211130_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prevent_exports', models.BooleanField(default=False)),
            ],
        ),
    ]

