# Generated by Django 2.2.28 on 2022-05-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220209_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livesettings',
            options={'verbose_name_plural': 'Live settings'},
        ),
    ]
