# Generated by Django 3.2.14 on 2022-07-05 17:19

import django.core.validators
from django.db import migrations, models
import main.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220527_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontitle',
            name='public_url',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-\\w]+\\Z'), 'Enter a valid “slug” consisting of Unicode letters, numbers, underscores, or hyphens.', 'invalid'), main.models.validate_unused_prefix]),
        ),
    ]
