# Generated by Django 3.2.14 on 2022-07-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_post_32_upgrade'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentannotation',
            name='main_conten_resourc_38f18b_idx',
        ),
        migrations.RemoveField(
            model_name='contentannotation',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='contentannotation',
            name='end_paragraph',
        ),
        migrations.RemoveField(
            model_name='contentannotation',
            name='start_offset',
        ),
        migrations.RemoveField(
            model_name='contentannotation',
            name='start_paragraph',
        ),
        migrations.RemoveField(
            model_name='historicalcontentannotation',
            name='end_offset',
        ),
        migrations.RemoveField(
            model_name='historicalcontentannotation',
            name='end_paragraph',
        ),
        migrations.RemoveField(
            model_name='historicalcontentannotation',
            name='start_offset',
        ),
        migrations.RemoveField(
            model_name='historicalcontentannotation',
            name='start_paragraph',
        ),
        migrations.AddIndex(
            model_name='contentannotation',
            index=models.Index(fields=['resource'], name='main_conten_resourc_c48efc_idx'),
        ),
    ]
