# Generated by Django 3.2.14 on 2022-07-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_drop_legacy_annotation_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='raw_headnote',
        ),
        migrations.RemoveField(
            model_name='historicalcontentnode',
            name='raw_headnote',
        ),
    ]
