# Generated by Django 3.2.14 on 2022-07-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_drop_raw_headnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltextblock',
            name='created_via_import',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='created_via_import',
        ),
    ]
