# Generated by Django 3.2.14 on 2022-07-06 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_drop_created_via_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltextblock',
            name='public',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='public',
        ),
    ]
