# Generated by Django 2.2.9 on 2020-01-07 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200107_1858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Default',
            new_name='Link',
        ),
    ]
