# Generated by Django 2.2.9 on 2020-01-07 20:50

from django.db import migrations

def resource_type_is_now_link(apps, schema_editor):
    ContentNode = apps.get_model('main', 'ContentNode')
    ContentNode.objects.filter(resource_type='Default').update(resource_type='Link')

def revert(apps, schema_editor):
    ContentNode = apps.get_model('main', 'ContentNode')
    ContentNode.objects.filter(resource_type='Link').update(resource_type='Default')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200107_2023'),
    ]

    operations = [
        migrations.RunPython(resource_type_is_now_link, revert),
    ]
