# Generated by Django 3.2.14 on 2022-07-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_drop_public_on_textblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CkeditorAsset',
        ),
        migrations.DeleteModel(
            name='ContentImage',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='MediaType',
        ),
    ]
