# Generated by Django 2.2.9 on 2020-01-08 15:14

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200107_2050'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='role',
            name='roles_name_a96913_idx',
        ),
        migrations.RemoveIndex(
            model_name='textblock',
            name='text_blocks_created_d06320_idx',
        ),
        migrations.RemoveIndex(
            model_name='textblock',
            name='text_blocks_name_ce27bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='textblock',
            name='text_blocks_updated_9ac1a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_affilia_021728_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_attribu_e12b66_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_a_f58eef_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_id_6a15a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_last_re_e753cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentnode',
            name='content_nod_ancestr_752d0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentnode',
            name='content_nod_caseboo_fd87f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentnode',
            name='content_nod_resourc_12667a_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_case_co_b58acb_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_citatio_b60de2_gin',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_created_6583ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_decisio_c6e645_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_name_ab_2ffab3_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_public_2d5cec_idx',
        ),
        migrations.RemoveIndex(
            model_name='case',
            name='cases_updated_395104_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentannotation',
            name='content_ann_resourc_a9fa0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='casecourt',
            name='case_courts_name_8b0202_idx',
        ),
        migrations.RemoveIndex(
            model_name='casecourt',
            name='case_courts_name_ab_48fee9_idx',
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['name'], name='main_role_name_452b83_idx'),
        ),
        migrations.AddIndex(
            model_name='textblock',
            index=models.Index(fields=['created_at'], name='main_textbl_created_024e46_idx'),
        ),
        migrations.AddIndex(
            model_name='textblock',
            index=models.Index(fields=['name'], name='main_textbl_name_f2ba11_idx'),
        ),
        migrations.AddIndex(
            model_name='textblock',
            index=models.Index(fields=['updated_at'], name='main_textbl_updated_f064c6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['affiliation'], name='main_user_affilia_66dba6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['attribution'], name='main_user_attribu_5ecf14_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email_address'], name='main_user_email_a_eb9d5b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='main_user_id_2f97ab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_request_at'], name='main_user_last_re_6a44f6_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['ancestry'], name='main_conten_ancestr_30f66b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['casebook', 'ordinals'], name='main_conten_caseboo_dcb214_idx'),
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['resource_type', 'resource_id'], name='main_conten_resourc_697521_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_court'], name='main_case_case_co_437839_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=django.contrib.postgres.indexes.GinIndex(fields=['citations'], name='main_case_citatio_1ccae9_gin'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='main_case_created_564e30_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['decision_date'], name='main_case_decisio_73ca2b_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['name_abbreviation'], name='main_case_name_ab_9ce903_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['public'], name='main_case_public_7032ab_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['updated_at'], name='main_case_updated_8871a3_idx'),
        ),
        migrations.AddIndex(
            model_name='contentannotation',
            index=models.Index(fields=['resource', 'start_paragraph'], name='main_conten_resourc_38f18b_idx'),
        ),
        migrations.AddIndex(
            model_name='casecourt',
            index=models.Index(fields=['name'], name='main_caseco_name_cdb6f6_idx'),
        ),
        migrations.AddIndex(
            model_name='casecourt',
            index=models.Index(fields=['name_abbreviation'], name='main_caseco_name_ab_06b7cf_idx'),
        ),
        migrations.AlterModelTable(
            name='case',
            table=None,
        ),
        migrations.AlterModelTable(
            name='casecourt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contentannotation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contentcollaborator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='contentnode',
            table=None,
        ),
        migrations.AlterModelTable(
            name='link',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rawcontent',
            table=None,
        ),
        migrations.AlterModelTable(
            name='role',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rolesuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='textblock',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
