# Generated by Django 3.2.14 on 2022-07-14 17:36

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_drop_legacy_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullTextSearchIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('document', django.contrib.postgres.search.SearchVectorField()),
                ('metadata', models.JSONField()),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'fts_internal_search_view',
                'managed': False,
            },
        ),
    ]
