# Generated by Django 3.2.14 on 2022-07-14 17:47

from django.db import migrations, models
import main.models
import main.storages


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_fulltextsearchindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebook',
            name='cover_image',
            field=models.FileField(blank=True, null=True, storage=main.storages.S3Storage(access_key='accesskey', bucket_name='h2o.images', endpoint_url='http://opencasebook.minio.test:9000', secret_key='secretkey'), upload_to=main.models.cover_image_path),
        ),
        migrations.AddField(
            model_name='historicalcasebook',
            name='cover_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedimage',
            name='image',
            field=models.FileField(storage=main.storages.S3Storage(access_key='accesskey', bucket_name='h2o.images', endpoint_url='http://opencasebook.minio.test:9000', secret_key='secretkey'), upload_to=''),
        ),
    ]
