# Generated by Django 3.2.14 on 2022-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20220714_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='reading_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicalcontentnode',
            name='reading_length',
            field=models.IntegerField(null=True),
        ),
    ]
