# Generated by Django 3.2.14 on 2022-07-19 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_reading_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebook',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(750)]),
        ),
        migrations.AddField(
            model_name='historicalcasebook',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(750)]),
        ),
    ]
