# Generated by Django 3.2.14 on 2022-08-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_casebook_description_20220719_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesettings',
            name='enable_printable_html_export',
            field=models.BooleanField(default=False, help_text='Enable the view to export entire casebooks as HTML'),
        ),
    ]
