# Generated by Django 2.2.9 on 2020-01-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200108_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='cloneable',
        ),
    ]
