# Generated by Django 3.2.15 on 2022-08-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_setting_for_html_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltextblock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='description',
        ),
    ]
