# Generated by Django 2.2.9 on 2020-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200108_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='title',
            field=models.CharField(default='Untitled', max_length=10000),
        ),
    ]
