# Generated by Django 2.2.9 on 2020-01-13 21:06
from django.db import migrations
from ..utils import clone_model_instance

def copy_common_resources(apps, schema_editor):
    ContentNode = apps.get_model('main', 'ContentNode')
    resource_types = set(['Link', 'TextBlock'])
    for resource_type in resource_types:
        resource_class = apps.get_model('main', resource_type)
        seen = set()
        for cn in ContentNode.objects.filter(resource_type=resource_type):
            if cn.resource_id:
                if cn.resource_id in seen:
                    duplicate = clone_model_instance(resource_class.objects.filter(id=cn.resource_id).first())
                    duplicate.save()
                    cn.resource_id = duplicate.id
                    cn.save()
                seen.add(cn.resource_id)

def cannot_reverse():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200108_2017'),
    ]

    operations = [
        migrations.RunPython(copy_common_resources, cannot_reverse)
    ]
