# Generated by Django 3.2.14 on 2022-08-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_add_instructional_content_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_site',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AddField(
            model_name='user',
            name='short_bio',
            field=models.CharField(blank=True, max_length=511),
        ),
    ]
