# Generated by Django 3.2.15 on 2022-08-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='is_instructional_material',
            field=models.BooleanField(default=False, help_text='This content should only be made available on the front end to verified professors'),
        ),
        migrations.AlterField(
            model_name='historicalcontentnode',
            name='is_instructional_material',
            field=models.BooleanField(default=False, help_text='This content should only be made available on the front end to verified professors'),
        ),
    ]
