# Generated by Django 3.2.15 on 2022-09-26 20:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_instructional_material_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=1000, unique=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('email_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text="A list of valid email domains for this institutions quoted and in brackets, e.g. ['harvard.edu', 'law.harvard.edu']", size=None)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.institution'),
        ),
    ]
