# Generated by Django 2.2.9 on 2020-02-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_contentcollaborator_can_edit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentnode',
            name='main_conten_ancestr_30f66b_idx',
        ),
        migrations.RemoveField(
            model_name='contentnode',
            name='ancestry',
        ),
        migrations.RemoveField(
            model_name='contentnode',
            name='root_user',
        ),
    ]
