# Generated by Django 3.2.15 on 2022-10-11 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_initial_institution_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesettings',
            name='enable_printable_html_export',
        ),
    ]
