# Generated by Django 2.2.10 on 2020-03-03 15:28

from django.db import migrations, models
from main.models import Case

def populate_court_names(app, schema):
    for case in Case.objects.select_related('case_court').all():
        case.court_name = case.case_court and case.case_court.name
        case.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20200212_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='ancestry',
        ),
        migrations.AddField(
            model_name='case',
            name='court_name',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.RunPython(populate_court_names, migrations.RunPython.noop)
    ]
