# Generated by Django 2.2.10 on 2020-03-04 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20200303_1528'),
    ]

    operations = [
        migrations.DeleteModel(name="CaseCourt")
    ]
