# Generated by Django 3.2.16 on 2022-11-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_drop_printable_livesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallink',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='content_type',
        ),
    ]
