# Generated by Django 3.2.16 on 2023-01-09 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_drop_link_content_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasebookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('casebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.casebook')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_text', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, choices=[('institution', 'Institution'), ('resource_type', 'Resource Type'), ('interest_area', 'Interest Area')], max_length=100)),
                ('casebooks', models.ManyToManyField(related_name='tags', through='main.CasebookTag', to='main.Casebook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casebooktag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag'),
        ),
        migrations.AlterUniqueTogether(
            name='casebooktag',
            unique_together={('tag', 'casebook')},
        ),
    ]
