# Generated by Django 3.2.18 on 2023-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_add_casebook_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='doc_class',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='effective_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='publication_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicallegaldocument',
            name='source_ref',
            field=models.CharField(db_index=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='doc_class',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='effective_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='publication_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='source_ref',
            field=models.CharField(db_index=True, max_length=10000),
        ),
    ]
