# Generated by Django 2.2.10 on 2020-03-09 16:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200309_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCase',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name_abbreviation', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('public', models.BooleanField(blank=True, default=False, null=True)),
                ('created_via_import', models.BooleanField(default=False)),
                ('capapi_id', models.IntegerField(blank=True, null=True)),
                ('attorneys', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('parties', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('opinions', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('citations', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('docket_number', models.CharField(blank=True, max_length=20000, null=True)),
                ('header_html', models.CharField(blank=True, max_length=15360, null=True)),
                ('content', models.CharField(max_length=5242880)),
                ('court_name', models.CharField(blank=True, max_length=1024, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
