# Generated by Django 2.2.10 on 2020-03-12 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20200312_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCollaborator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('has_attribution', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('casebook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Casebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'casebook')},
            },
        ),
        migrations.AddField(
            model_name='casebook',
            name='collaborators',
            field=models.ManyToManyField(related_name='casebooks', through='main.TempCollaborator', to=settings.AUTH_USER_MODEL),
        ),
    ]
