# Generated by Django 2.2.10 on 2020-03-12 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200312_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentnode',
            name='new_casebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contents', to='main.Casebook'),
        ),
    ]
