# Generated by Django 2.2.10 on 2020-04-09 11:28

from django.db import migrations
from main.models import ContentNode

def deref_old_casebooks(app,schema):
    bulk_nodes = []
    old_to_new_cbs = {}
    for node in ContentNode.objects.order_by('casebook_id').all():
        if node.casebook_id:
            if node.casebook_id in old_to_new_cbs and node.casebook_id != old_to_new_cbs[node.casebook_id]:
                node.casebook = None
                bulk_nodes.append(node)
            else:
                old_to_new_cbs[node.casebook_id] = node.casebook_id
    ContentNode.objects.bulk_update(bulk_nodes, ['casebook_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_casebook_provenance'),
    ]

    operations = [
        migrations.RunPython(deref_old_casebooks, migrations.RunPython.noop),
    ]
