# Generated by Django 2.2.10 on 2020-04-20 20:48

from django.db import migrations
from main.models import Casebook

def casebook_provenance(app, schema):
    cb_map = {cb.old_casebook_id: cb.id for cb in Casebook.objects.all() if cb.old_casebook_id}
    bulk_cbs = []
    for cb in Casebook.objects.all():
        if cb.provenance:
            cb.provenance = [cb_map.get(x,x) for x in cb.provenance]
            bulk_cbs.append(cb)
    Casebook.objects.bulk_update(bulk_cbs, ['provenance'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_migrate_casebook_dates'),
    ]

    operations = [
        migrations.RunPython(casebook_provenance, migrations.RunPython.noop)
    ]
