# Generated by Django 2.2.10 on 2020-05-15 12:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20200420_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('university_url', models.URLField(max_length=1024)),
                ('email_domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='casebook',
            name='state',
            field=models.CharField(choices=[(main.models.Casebook.LifeCycle('Fresh'), 'Fresh'), (main.models.Casebook.LifeCycle('Clone'), 'Clone'), (main.models.Casebook.LifeCycle('Draft'), 'Draft'), (main.models.Casebook.LifeCycle('Public'), 'Public'), (main.models.Casebook.LifeCycle('Archived'), 'Archived'), (main.models.Casebook.LifeCycle('Revising'), 'Revising')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcasebook',
            name='state',
            field=models.CharField(choices=[(main.models.Casebook.LifeCycle('Fresh'), 'Fresh'), (main.models.Casebook.LifeCycle('Clone'), 'Clone'), (main.models.Casebook.LifeCycle('Draft'), 'Draft'), (main.models.Casebook.LifeCycle('Public'), 'Public'), (main.models.Casebook.LifeCycle('Archived'), 'Archived'), (main.models.Casebook.LifeCycle('Revising'), 'Revising')], max_length=10),
        ),
    ]
