# Generated by Django 2.2.13 on 2020-07-30 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20200515_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='casebook',
            name='edition_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historicalcasebook',
            name='edition_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contentnode',
            name='casebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='old_casebook_contents', to='main.ContentNode'),
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=300)),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='title_name', to='main.Casebook')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
