# Generated by Django 2.2.13 on 2020-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20200730_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
