# Generated by Django 2.2.13 on 2020-08-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200804_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='public_url',
        ),
    ]
