# Generated by Django 2.2.13 on 2020-08-09 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200804_1647'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='CommonTitle',
        ),
        migrations.AddField(
            model_name='casebook',
            name='common_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='casebooks', to='main.CommonTitle'),
        ),
        migrations.AddField(
            model_name='historicalcasebook',
            name='common_title',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.CommonTitle'),
        ),
    ]
