# Generated by Django 2.2.13 on 2020-08-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_auto_20200809_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commontitle',
            old_name='slug',
            new_name='public_url',
        ),
    ]
