# Generated by Django 2.2.13 on 2020-08-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20200810_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebook',
            name='common_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casebooks', to='main.CommonTitle'),
        ),
    ]
