# Generated by Django 2.2.13 on 2020-08-24 12:43

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200811_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebook',
            name='state',
            field=models.CharField(choices=[(main.models.Casebook.LifeCycle('Fresh'), 'Fresh'), (main.models.Casebook.LifeCycle('Clone'), 'Clone'), (main.models.Casebook.LifeCycle('Draft'), 'Draft'), (main.models.Casebook.LifeCycle('Public'), 'Public'), (main.models.Casebook.LifeCycle('Archived'), 'Archived'), (main.models.Casebook.LifeCycle('Revising'), 'Revising'), (main.models.Casebook.LifeCycle('Previous'), 'Previous')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcasebook',
            name='state',
            field=models.CharField(choices=[(main.models.Casebook.LifeCycle('Fresh'), 'Fresh'), (main.models.Casebook.LifeCycle('Clone'), 'Clone'), (main.models.Casebook.LifeCycle('Draft'), 'Draft'), (main.models.Casebook.LifeCycle('Public'), 'Public'), (main.models.Casebook.LifeCycle('Archived'), 'Archived'), (main.models.Casebook.LifeCycle('Revising'), 'Revising'), (main.models.Casebook.LifeCycle('Previous'), 'Previous')], max_length=10),
        ),
    ]
