# Generated by Django 2.2.13 on 2020-08-24 14:32

from django.db import migrations, models
import django.db.models.deletion
from main.models import Casebook


def trim_clone_drafts(app, schema):
    cbs = [x for x in Casebook.objects.filter(draft__isnull=False).order_by('id').all()]
    seen = set()
    for cb in cbs:
        if cb.draft in seen:
            cb.draft = None
            cb.save()
        else:
            seen.add(cb.draft)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20200824_1243'),
    ]

    operations = [
        migrations.RunPython(trim_clone_drafts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='casebook',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draft_of', to='main.Casebook', unique=True),
        ),
    ]
