# Generated by Django 2.2.13 on 2020-08-24 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20200824_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebook',
            name='draft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draft_of', to='main.Casebook'),
        ),
    ]
