# Generated by Django 2.2.13 on 2020-08-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20200824_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casebook',
            name='state',
            field=models.CharField(choices=[('Fresh', 'PRIVATELY_EDITING'), ('Clone', 'NEWLY_CLONED'), ('Draft', 'DRAFT'), ('Public', 'PUBLISHED'), ('Archived', 'ARCHIVED'), ('Revising', 'REVISING'), ('Previous', 'PREVIOUS_SAVE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalcasebook',
            name='state',
            field=models.CharField(choices=[('Fresh', 'PRIVATELY_EDITING'), ('Clone', 'NEWLY_CLONED'), ('Draft', 'DRAFT'), ('Public', 'PUBLISHED'), ('Archived', 'ARCHIVED'), ('Revising', 'REVISING'), ('Previous', 'PREVIOUS_SAVE')], max_length=10),
        ),
    ]
