# Generated by Django 2.2.13 on 2020-08-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200825_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltextblock',
            name='content',
            field=models.CharField(blank=True, default='', max_length=5242880),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='content',
            field=models.CharField(blank=True, default='', max_length=5242880),
        ),
    ]
