# Generated by Django 2.2.16 on 2020-10-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20200825_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentnode',
            name='collaborators',
        ),
        migrations.DeleteModel(
            name='ContentCollaborator',
        ),
    ]
