# Generated by Django 2.2.16 on 2020-10-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20201013_1259'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentnode',
            name='main_conten_caseboo_dcb214_idx',
        ),
        migrations.RenameField(
            model_name='contentnode',
            old_name='casebook',
            new_name='old_casebook',
        ),
        migrations.RenameField(
            model_name='historicalcontentnode',
            old_name='casebook',
            new_name='old_casebook',
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['new_casebook', 'ordinals'], name='main_conten_new_cas_966f97_idx'),
        ),
    ]
