# Generated by Django 2.2.16 on 2020-10-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20201013_1900'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentnode',
            name='main_conten_new_cas_966f97_idx',
        ),
        migrations.RenameField(
            model_name='contentnode',
            old_name='new_casebook',
            new_name='casebook',
        ),
        migrations.RenameField(
            model_name='historicalcontentnode',
            old_name='new_casebook',
            new_name='casebook',
        ),
        migrations.AddIndex(
            model_name='contentnode',
            index=models.Index(fields=['casebook', 'ordinals'], name='main_conten_caseboo_dcb214_idx'),
        ),
    ]
