# Generated by Django 3.2.14 on 2022-07-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0030_reading_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.user',),
        ),
        migrations.CreateModel(
            name='ReportingCasebook',
            fields=[
            ],
            options={
                'verbose_name': 'Casebook',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.casebook',),
        ),
        migrations.CreateModel(
            name='CasebookCAP',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with CAP content',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookCAPProf',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with CAP content byprofessor',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookCollaborators',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with any collaborator',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookCollaboratorsProf',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with professors as collaborator',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookGPO',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with GPO content',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookGPOProf',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks with GPO content by professor',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookProfessors',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks from professor',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookSeries',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks in series',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='CasebookSeriesProf',
            fields=[
            ],
            options={
                'verbose_name': 'Casebooks in series by professors',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.reportingcasebook',),
        ),
        migrations.CreateModel(
            name='ProfessorWithCasebooks',
            fields=[
            ],
            options={
                'verbose_name': 'Professors with casebook',
                'ordering': ('created_at',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('reporting.professor',),
        ),
    ]
