development:
  adapter: async

test:
  adapter: async

production: &production_defaults
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: h2o_production

staging:
  <<: *production_defaults
