name: Build images

on: workflow_dispatch

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push docker images
        uses: harvard-lil/lil-actions/docker-compose-update@main
        with:
          registry: "ghcr.io"
          registry-user: ${{ github.actor }}
          registry-pass: ${{ secrets.GITHUB_TOKEN }}
          bake-action: "push"
